post:
  tags:
    - products
  summary: create a new product docx file
  description: Creates a single product and returns a docx file
  operationId: getDocxForSingleProduct
  requestBody:
    description: product as request body
    required: true
    content:
      application/json:
        schema:
          $ref: "../models/singleProduct.yml#/SingleProduct"
  responses:
    200:
      description: OK
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary
    204:
      description: The docx file for single product was created successfully.