post:
  tags:
    - products
  summary: create a new multi products zip file
  description: Creates multiple products for one project and zips them in a temporary zip file
  operationId: getZipForMultiProducts
  requestBody:
    description: multi products as request body
    required: true
    content:
      application/json:
        schema:
          $ref: "../models/multiProducts.yml#/MultiProducts"
  responses:
    200:
      description: OK
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary
    204:
      description: The zip file for multi products was created successfully.