openapi: 3.0.3
info:
  title: projektassistent-openapi
  version: 0.2.5.rc1
servers:
  - url: http://localhost:9081/api/v1
    description: Development
components:
  schemas:
    ChapterEntry:
      $ref: "models/chapterEntry.yml"
paths:
  /status:
    $ref: "paths/status.yml"
  /product:
    $ref: "paths/product.yml"
  /products:
    $ref: "paths/products.yml"
