openapi: 3.0.3
info:
  title: projektassistent-openapi
  version: 0.2.4
servers:
  - url: http://localhost:9081/api/v1
    description: Development
definitions:
  DataEntry:
    $ref: "./dataEntry.yml#/DataEntry"
  PageEntry:
    $ref: "./pageEntry.yml#/PageEntry"
  ProjectFeature:
    $ref: "./projectFeature.yml#/ProjectFeature"
  TableEntry:
    $ref: "./tableEntry.yml#/TableEntry"
paths:
  /status:
    $ref: "paths/status.yml"
  /modelVariants/{metaModelId}:
    $ref: "paths/modelVariants.yml"
  /projectTypes/{metaModelId}/{modelVariantId}:
    $ref: "paths/projectTypes.yml"
  /projectTypeVariants/{metaModelId}/{modelVariantId}:
    $ref: "paths/projectTypeVariants.yml"
  /menuEntries:
    $ref: "paths/menuEntry.yml"
